Repository phoenixframework/phoenix_live_view, pull requests merged in 2019-08, with the labels that each got.

#293 Update morphdom 2.5.5 - solve live_render in tables
  assets/package-lock.json
  assets/package.json
Labels: awaiting feedback, enhancement

#131 Significantly improve performance on par with virtual dom diffing
  assets/js/phoenix_live_view.js
  priv/static/phoenix_live_view.js
Labels: awaiting feedback, enhancement

#291 BUGFIX: typeof object check prevent null
  assets/js/phoenix_live_view.js
  priv/static/phoenix_live_view.js
Labels: awaiting feedback, enhancement

#149 Moar JS tests
  assets/.gitignore
  assets/package.json
  assets/test/live_socket_test.js
  assets/test/view_test.js
Labels: awaiting feedback, enhancement

#295 Use container tag name for diffing
  assets/js/phoenix_live_view.js
  priv/static/phoenix_live_view.js
Labels: enhancement

#236 fix replacing mixed data types
  assets/js/phoenix_live_view.js
  assets/test/rendered_test.js
  priv/static/phoenix_live_view.js
Labels: bug
